package Model;
// Generated 16-May-2024 23:18:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;


/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private Integer nrMatricula;
  
     private Turma turma;
     private String nome;
     private String apelido;
     private String endereco;
     private String contacto;
     private Set realizas = new HashSet(0);

    public Estudante() {
    }

    public Estudante(Turma turma, String nome, String apelido, String endereco, String contacto, Set realizas) {
       this.turma = turma;
       this.nome = nome;
       this.apelido = apelido;
       this.endereco = endereco;
       this.contacto = contacto;
       this.realizas = realizas;
    }
   
    public Integer getNrMatricula() {
        return this.nrMatricula;
    }
    
    public void setNrMatricula(Integer nrMatricula) {
        this.nrMatricula = nrMatricula;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }

// No arquivo Estudante.java

// Adicione este método para obter os detalhes do estudante como uma string formatada
public String getDetalhes() {
    // Monta uma string com os detalhes do estudante
    return "Número de Matrícula: " + this.getNrMatricula() +
            ", Nome: " + this.getNome() +
            ", Apelido: " + this.getApelido() +
            ", Endereço: " + this.getEndereco() +
            ", Contato: " + this.getContacto();
}



}


