package Model;
// Generated 16-May-2024 23:18:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer id;
     private Curso curso;
     private String nome;
     private Set estudantes = new HashSet(0);

    public Turma() {
    }

	
    public Turma(Curso curso) {
        this.curso = curso;
    }
    public Turma(Curso curso, String nome, Set estudantes) {
       this.curso = curso;
       this.nome = nome;
       this.estudantes = estudantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }




}


